---
title: "Reading Delimited Data"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---
# Task 2 Reading Delimited Data
- read data, add column name and print out tibble
```{r}
library(readr)
glass_data <- read_csv("https://www4.stat.ncsu.edu/online/datasets/glass.data",
col_names = c("Id", "RI", "Na", "Mg", "Al", "Si", "K", "Ca", "Ba", "Fe","Type_of_glass"))
glass_data
```
-  Rewrite variable "Type_of_glass" values 
```{r}
library(dplyr)
glass_data|>
  mutate(Type_of_glass=if_else(Type_of_glass == 1, "building_windows_float_processed", 
 if_else(Type_of_glass == 2, "building_windows_non_float_processed",
         if_else(Type_of_glass == 3, "vehicle_windows_float_processed",
                 if_else(Type_of_glass == 4, "vehicle_windows_non_float_processed",
                         if_else(Type_of_glass == 5, "containers",
                                 if_else(Type_of_glass == 6, "tableware",
                                         if_else(Type_of_glass == 7, "headlamps",
                                                         as.character(Type_of_glass))))))))) |> 
  filter(Fe < 0.2,Type_of_glass %in% c("tableware", "headlamps"))|>print()

```
- Yeast Data
-  read data, add column name and print out tibble
```{r}
yeast_data <- read_fwf(file="https://www4.stat.ncsu.edu/online/datasets/yeast.data", fwf_widths(c(10,4,4,4,4,4,4,4,4,3),c("seq_name","mcg", "gvh", "alm", "mit", "erl", "pox", "vac", "nuc","class")))

  yeast_data

```
-  Remove columns, add mean and median to the numeric columns and group by class

```{r}
library(dplyr)
yeast_data |> select(-c(seq_name,nuc))|> group_by(class)|>  mutate(across(where(is.numeric),list(mean=mean,median=median), .names = "{.col}_{.fn}"))
```

